name: 'Drupal Actions'
description: 'Run PHPUnit tests, PHPCS, and PHPStan analysis for Drupal 10 projects in a Drupal container'
author: 'skyredwang on drupal.org'
branding:
  icon: 'check-circle'
  color: 'blue'
inputs:
  drupal_version:
    description: 'Drupal version'
    required: false
    default: 'latest'
  php_version:
    description: 'PHP version to use'
    required: false
    default: '8.3'
  mysql_version:
    description: 'MySQL version to use'
    required: false
    default: 'latest'
  phpunit_coverage_path:
    description: 'Path for PHPUnit coverage output'
    required: false
    default: 'coverage'
  phpunit_config_file:
    description: 'PHPUnit configuration file'
    required: false
    default: 'phpunit.xml'
  test_target_directory:
    description: 'Target directory for tests'
    required: false
    default: ''
  junit_path:
    description: 'Path for JUnit output'
    required: false
    default: 'junit'
  simpletest_db:
    description: 'Database connection string for Simpletest'
    required: false
    default: 'mysql://root:mysql_strong_password@mysql/drupal'
  browsertest_output_directory:
    description: 'Browser test output directory'
    required: false
    default: '.tmp/browser_output'
  simpletest_base_url:
    description: 'Base URL for Simpletest'
    required: false
    default: 'http://localhost'
  phpcs_config_file:
    description: 'PHPCS configuration file'
    required: false
    default: 'phpcs.xml'
  phpcs_target_directory:
    description: 'Target directory for PHPCS'
    required: false
    default: 'modules/custom themes/custom'
  phpstan_config_file:
    description: 'PHPStan configuration file'
    required: false
    default: 'phpstan.neon'
runs:
  using: 'workflow'
  main: '.github/workflows/phpunit-coverage.yml'